### ISSUE TITLE
工具在canvas操作时，都有偏移，请帮忙看是什么原因

### ISSUE THREAD

**Issue by cag2050** [S-mohan/captures-tools#1]
我用您的这个工具，写了一个demo，demo地址：https://github.com/cag2050/canvastools_demo
工具在canvas操作时，都有偏移，请您帮忙看是什么原因。

**Comment by amaneru55** [comment]
把dist/canvastools.js line 694、695改成
	var x = event.clientX - rect.left * 5 / 4 + (event.clientX / rect.offsetWidth) * (rect.width - rect.offsetWidth);
	var y = event.clientY - rect.top * 5 / 4 + (event.clientY / rect.offsetHeight) * (rect.height - rect.offsetHeight);
即可
