### ISSUE TITLE
文字输入，不能自动换行，

### ISSUE THREAD

**Issue by yixiyimeng** [S-mohan/captures-tools#5]
我在文本中使用enter键换行，canvas画图后，enter，转换为空格，未能成功换行

**Comment by S-mohan** [comment]
> 我在文本中使用enter键换行，canvas画图后，enter，转换为空格，未能成功换行

文字部分只处理了自动换行的，手动换行的没有处理，可以修改此处代码，https://github.com/S-mohan/canvasTools/blob/master/src/js/main.js#L581 ， 针对\r\n做相关处理
